name: Upload data.parquet to S3

on:
  workflow_run:
    workflows: ["Terraform Workflow"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do códigoo
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Configurar o AWS CLII
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # Passo 3: Fazer o upload do arquivo data.parquet para o S3
      - name: Upload data.parquet to S3
        run: |
          aws s3 cp data.parquet s3://career-path-terraform-studies/data/data.parquet --region us-east-1

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run Glue Crawler
        run: |
          aws glue start-crawler --name career-path-crawler --region us-east-1
  
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}