name: Terraform Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do código
      - name: Checkout the code
        uses: actions/checkout@v2

      # Passo 2: Configurar o Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false


      # Passo 3: Inicializar o Terraform
      - name: Terraform destroy
        run: terraform destroy
        working-directory: terraform

      # Passo 3: Inicializar o Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      # Passo 4: Executar Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Passo 5: Executar Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Passo 6: Instalar o AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli

      # Passo 7: Configurar AWS CLI
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1

      # Passo 8: Verificar se o bucket foi criado com AWS CLI
      - name: Verificar Bucket S3
        run: aws s3 ls --region us-east-1 --debug
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
