name: Upload file to s3

on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform init
      run: terraform init
      working-directory: terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform 

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Upload file to s3
      env:
        AWS_ACCESS_KEY_ID: mock
        AWS_SECRET_ACCESS_KEY: mock
      run: |
        aws s3 cp data.json s3://career-path-terraform/data.json --endpoint-url=http://localhost:4566